/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/vaadin-grid-pro-inline-editing-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {microTask} from '@polymer/polymer/lib/utils/async.js';

import {Debouncer} from '@polymer/polymer/lib/utils/debounce.js';

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

export {InlineEditingMixin};

declare function InlineEditingMixin<T extends new (...args: any[]) => {}>(base: T): T & InlineEditingMixinConstructor;

interface InlineEditingMixinConstructor {
  new(...args: any[]): InlineEditingMixin;
}

export {InlineEditingMixinConstructor};

interface InlineEditingMixin {

  /**
   * When true, pressing Enter while in cell edit mode
   * will move focus to the editable cell in the next row
   * (Shift + Enter - same, but for previous row).
   * @attr {boolean} enter-next-row
   */
  enterNextRow: boolean|null|undefined;

  /**
   * When true, after moving to next or previous editable cell using
   * Tab / Shift+Tab, it will be focused without edit mode.
   *
   * When `enterNextRow` is true, pressing Enter will also
   * preserve edit mode, otherwise, it will have no effect.
   * @attr {boolean} single-cell-edit
   */
  singleCellEdit: boolean|null|undefined;

  /**
   * When true, the grid enters cell edit mode on a single click
   * instead of the default double click.
   */
  editOnClick: boolean|null|undefined;
  ready(): void;
  _checkImports(): void;
  _stopEdit(shouldCancel?: boolean, shouldRestoreFocus?: boolean): void;
  _switchEditCell(e: KeyboardEvent): void;
  _updateItem(row: HTMLElement, item: GridItem|null): void;
}

import {GridItem} from '@vaadin/vaadin-grid/@types/interfaces';
